services:
  cnv:
    build: .
    ports:
      - "8001:8000"
    working_dir: /srv/CNV

  genealogy:
    build: .
    ports:
      - "8002:8000"
    working_dir: /srv/Genealogy

  snp:
    build: .
    ports:
      - "8003:8000"
    working_dir: /srv/SNP
